#!/bin/bash

# MindIE 多节点分布式环境变量默认值。
# 保持仅包含 export 命令；adapter 会将这些命令内联到 start_command.sh。

export PYTORCH_NPU_ALLOC_CONF="${PYTORCH_NPU_ALLOC_CONF:-expandable_segments:True}"
export OMP_NUM_THREADS="${OMP_NUM_THREADS:-10}"
export HCCL_DETERMINISTIC="${HCCL_DETERMINISTIC:-false}"
export HCCL_OP_EXPANSION_MODE="${HCCL_OP_EXPANSION_MODE:-AIV}"
export ATB_LLM_HCCL_ENABLE="${ATB_LLM_HCCL_ENABLE:-1}"
export ATB_LLM_COMM_BACKEND="${ATB_LLM_COMM_BACKEND:-hccl}"
export INF_NAN_MODE_ENABLE="${INF_NAN_MODE_ENABLE:-0}"
export ATB_WORKSPACE_MEM_ALLOC_ALG_TYPE="${ATB_WORKSPACE_MEM_ALLOC_ALG_TYPE:-3}"
export ATB_WORKSPACE_MEM_ALLOC_GLOBAL="${ATB_WORKSPACE_MEM_ALLOC_GLOBAL:-1}"
export TASK_QUEUE_ENABLE="${TASK_QUEUE_ENABLE:-2}"
export CPU_AFFINITY_CONF="${CPU_AFFINITY_CONF:-1}"
export ATB_LAYER_INTERNAL_TENSOR_REUSE="${ATB_LAYER_INTERNAL_TENSOR_REUSE:-1}"
export ATB_OPERATION_EXECUTE_ASYNC="${ATB_OPERATION_EXECUTE_ASYNC:-1}"
export ATB_CONVERT_NCHW_TO_ND="${ATB_CONVERT_NCHW_TO_ND:-1}"
export ATB_CONTEXT_WORKSPACE_SIZE="${ATB_CONTEXT_WORKSPACE_SIZE:-0}"
export ATB_LAUNCH_KERNEL_WITH_TILING="${ATB_LAUNCH_KERNEL_WITH_TILING:-1}"
export ATB_LLM_ENABLE_AUTO_TRANSPOSE="${ATB_LLM_ENABLE_AUTO_TRANSPOSE:-0}"
export ATB_LLM_LCOC_ENABLE="${ATB_LLM_LCOC_ENABLE:-0}"
export HCCL_CONNECT_TIMEOUT="${HCCL_CONNECT_TIMEOUT:-7200}"
export HCCL_EXEC_TIMEOUT="${HCCL_EXEC_TIMEOUT:-600}"
export ASCEND_GLOBAL_LOG_LEVEL="${ASCEND_GLOBAL_LOG_LEVEL:-3}"
export ASCEND_SLOG_PRINT_TO_STDOUT="${ASCEND_SLOG_PRINT_TO_STDOUT:-0}"
export MINDIE_LOG_TO_STDOUT=1